### ISSUE TITLE
Request for Permission to Write and Open-Source a Library Based on Your Repository

### ISSUE THREAD

**Issue by Molth** [Cysharp/KcpTransport#3]
I am interested in building and open-sourcing a new library based on your project. I admire your work and believe I can contribute to the community by adding new functionalities built upon its foundation.
My plan is to create a new library that will contain some wrappers for unity mirror or netcode for gameobjects. 
Before proceeding, I would like to confirm if you permit me to use your project as a base and release my new library under a mit license. I will ensure to include appropriate copyright notices and acknowledgments to your project in the new library.
If you agree to this request, please let me know which license you think would be most suitable. I look forward to your response and will follow your guidance and instructions promptly.
Thank you for your time and consideration!
Best regards.

**Comment by neuecc** [comment]
Thank you.
Since this project is still in alpha, there are likely some areas that have remaining issues if used as a base.
As long as you're aware of that, there's no problem with creating derivatives.
I'm glad you're leaving the information.

**Comment by Molth** [comment]
Thank you very much for your response and support! Based on your agreement, I will release the new library under the MIT license and ensure it includes appropriate copyright notices and acknowledgments to your project. 
Thanks again for your time and assistance! 
Best regards.
